# -*- coding: utf-8 -*-
"""2a_Atividade_AyrttonLucas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZerum5p0njtK06JKFgqKG5GwurF_Hve
"""

from sklearn import preprocessing
import pandas as pd
from seaborn import load_dataset
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler
import numpy as np

"""## Carregar a base TITANIC do seaborn"""

df = load_dataset('titanic')

"""## Observar a quantidade de NaN existente no atributo "deck"
"""

df['deck'].isna().sum()

"""## Remover as linhas que tenham valores NaN"""

df.dropna(inplace = True)
df.drop(['deck'], axis = 1,inplace = True)

label_encoder = preprocessing.LabelEncoder()
df['class'] = label_encoder.fit_transform(df['class'])
df['class'] = df['class'] + 1

df.info()

"""## Observar a relação dos atributos "pclass" com "class"
"""

r2 = r2_score(df['pclass'], df['class'])
print('r2 score for perfect model is', r2)

"""## Transformar todos os atributos categóricos usando One-Hot Encoder

## Coluna target é a "pclass" ou "survived"
"""

y = df['survived']
df.drop(['survived'], axis = 1,inplace = True)

column_transformer = make_column_transformer((OneHotEncoder(), ['alone','alive','embark_town','adult_male','embarked', 'sex', 'who']), remainder='passthrough')
df = column_transformer.fit_transform(df)
df = pd.DataFrame(data=df, columns = column_transformer.get_feature_names_out())

X = df
df

"""## Separar os dados de treinamento e testes"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None, stratify = y)

"""## Treinar 2 árvores de decisão com características diferentes"""

def printTreino(model):
  result = model.predict(X_test)
  acc = metrics.accuracy_score(result, y_test)
  show = round(acc * 100)
  print("{}%".format(show))

model1 = DecisionTreeClassifier(criterion="entropy")
model1.fit(X_train, y_train)

printTreino(model1)

model2 = DecisionTreeClassifier(max_depth=2)
model2.fit(X_train, y_train)

printTreino(model2)

"""## Treinar 2 kNN com características diferentes"""

model3 = KNeighborsClassifier(n_neighbors=7, metric='euclidean', algorithm='brute')
model3.fit(X_train, y_train)

printTreino(model3)

model4 = KNeighborsClassifier(n_neighbors=7, algorithm='brute')
model4.fit(X_train, y_train)

printTreino(model4)

"""## Carregar a base TRANSFUSION. URL da base segue abaixo:"""

url = "https://raw.githubusercontent.com/tmoura/machinelearning/master/transfusion.data"

"""## A coluna 0 (zero) é o TARGET."""

dataset = pd.read_csv(url, header=None)
dataset

"""## Observe que a magnitude dos atributos é bem diferente, então cada atributo deve ser normalizado (código no mini tutorial de pandas)."""

for i in range (len(dataset.columns)):
  dataset[i] = MinMaxScaler().fit_transform(np.array(dataset[i]).reshape(-1,1))

columns = len(dataset.columns)

y = dataset[0] # extrai a primeira coluna, que é o label
X = dataset.loc[:,1:columns-1]

"""## Separar os dados de treinamento e testes"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=None, stratify=y) # 80% treino e 20% teste

"""## Treinar 2 árvores de decisão com características diferentes"""

model5 = DecisionTreeClassifier(criterion="entropy")
model5.fit(X_train, y_train)

printTreino(model5)

model6 = DecisionTreeClassifier(max_depth=2)
model6.fit(X_train, y_train)

printTreino(model6)

"""## Treinar 2 kNN com características diferentes"""

model7 = KNeighborsClassifier(n_neighbors=7, metric='euclidean', algorithm='brute')
model7.fit(X_train, y_train)

printTreino(model7)

model8 = KNeighborsClassifier(n_neighbors=7, algorithm='brute')
model8.fit(X_train, y_train)

printTreino(model8)